[package]
name = "print-10"
version = "0.1.0"
authors = ["nicolas <nicolas.sabbatini.95@gmail.com>"]
edition = "2018"

[dependencies]
macroquad = "0.3.0-alpha.17"

[profile.dev.package.'*']
opt-level = 3
